### ISSUE TITLE
Minor - patterns in SVG fills

### ISSUE THREAD

**Issue by ledow** [sammycage/plutosvg#15]
It appears that plutosvg doesn't render patterns in fills, this may be intentional.

The attached SVG (CC0 from https://www.me.uk/cards/ )
![1B](https://github.com/user-attachments/assets/78ecaaf5-c1e4-4dbe-8988-2cc2e23b3c77)

Renders as a white card:

![1B](https://github.com/user-attachments/assets/07b3032f-7aae-490b-8411-32ed110db126)

Where it should render as chequered (e.g. from an Inkscape export:

![1B](https://github.com/user-attachments/assets/7e41d369-ff99-4416-ae1b-44701e92f5c2)

Not a critical issue and I understand if it's entirely out of scope of plutosvg.

**Comment by sammycage** [comment]
Thank you for your feedback! PlutoSVG doesn't currently support patterns in fills due to limitations with the OpenType SVG specifications. If pattern rendering is important for your use case, I would recommend trying LunaSVG, which offers broader SVG rendering capabilities.

https://github.com/sammycage/lunasvg
